name: Test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Setup Surrealdb
        run: |
          docker run --rm --pull always -d \
            -p 5176:8000 \
            surrealdb/surrealdb:latest start \
            --user root --pass root
      - run: cargo test --verbose --all-features
